<?php

namespace App\Http\Controllers\Auth;

use App\Http\Controllers\Controller;
use App\Http\Requests\Auth\VerifyOtpRequest;
use App\Mail\OtpNotificationMail;
use App\Models\ActivityLog;
use App\Models\User;
use App\Services\OtpService;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Str;
use Illuminate\View\View;
use App\Events\SessionReplaced;

/**
 * OTP Verification Controller — Second Factor Authentication.
 *
 * Handles the OTP verification step that follows a successful password login.
 * Auth::login() is called HERE (not in AuthenticatedSessionController::store()),
 * ensuring that no authenticated session is established until OTP is verified.
 *
 * Session key: 'otp_pending_user_id'
 *   - Set by AuthenticatedSessionController::store() after password validation
 *   - Cleared here after successful OTP verification or upon abort
 *
 * SECURITY: The plaintext OTP is never stored anywhere. It is generated by
 * OtpService::generate(), used only to send the email, then discarded.
 */
class OtpVerificationController extends Controller
{
    public function __construct(
        private readonly OtpService $otpService,
    ) {}

    // ─────────────────────────────────────────── Show OTP Verification Page ──

    /**
     * Display the OTP verification form.
     *
     * Requires 'otp_pending_user_id' in session — redirects to login otherwise.
     */
    public function show(Request $request): View|RedirectResponse
    {
        $userId = $request->session()->get('otp_pending_user_id');

        if (! $userId) {
            return redirect()->route('login');
        }

        $user = User::find($userId);

        if (! $user || ! $user->is_active) {
            $request->session()->forget('otp_pending_user_id');
            return redirect()->route('login');
        }

        // Mask email for display — show only first 2 chars and domain
        // e.g. "dr.smith@hospital.com" → "dr****@hospital.com"
        $parts          = explode('@', $user->email);
        $localPart      = $parts[0] ?? '';
        $domain         = $parts[1] ?? '';
        $maskedLocal    = mb_substr($localPart, 0, 2) . str_repeat('*', max(0, mb_strlen($localPart) - 2));
        $maskedEmail    = $maskedLocal . '@' . $domain;

        // Get cooldown remaining for resend button
        $resendCooldown = $this->otpService->resendCooldownRemaining($user);

        return view('auth.otp-verify', [
            'maskedEmail'    => $maskedEmail,
            'expiresMinutes' => config('otp.expires_minutes', 3),
            'resendCooldown' => $resendCooldown,
        ]);
    }

    // ─────────────────────────────────────────── Verify Submitted OTP ──────

    /**
     * Process OTP verification.
     *
     * On success: completes full authentication (Auth::login, session regeneration,
     * active_session_id update, single-session replacement, audit log, role redirect).
     *
     * On failure: returns generic error — does not reveal internal state.
     */
    public function verify(VerifyOtpRequest $request): RedirectResponse
    {
        $userId = $request->session()->get('otp_pending_user_id');

        if (! $userId) {
            return redirect()->route('login');
        }

        $user = User::find($userId);

        if (! $user || ! $user->is_active) {
            $request->session()->forget('otp_pending_user_id');
            return redirect()->route('login');
        }

        // Verify the OTP via OtpService (handles hash check, expiry, attempt count)
        $result = $this->otpService->verify($user, $request->input('otp'));

        // ── Handle all non-success outcomes ────────────────────────────────
        if ($result === 'exhausted') {
            // 5 failed attempts — OTP is now unusable, user must restart
            $request->session()->forget('otp_pending_user_id');
            return redirect()->route('login')
                ->with('error', 'Too many incorrect attempts. Please sign in again to receive a new verification code.');
        }

        if ($result === 'expired') {
            // OTP has expired — redirect to resend
            return redirect()->route('otp.verify')
                ->withErrors(['otp' => 'The verification code is invalid or has expired.']);
        }

        if ($result === 'not_found' || $result === 'invalid') {
            // Generic message — do not reveal which condition triggered
            return redirect()->route('otp.verify')
                ->withErrors(['otp' => 'The verification code is invalid or has expired.']);
        }

        // ── OTP Verified — Complete authentication ──────────────────────────

        // Clear the OTP pending state before creating the authenticated session
        $request->session()->forget('otp_pending_user_id');

        // Full login — this is the ONLY place Auth::login() is called
        Auth::login($user);

        // Prevent session fixation by regenerating the session ID
        $request->session()->regenerate();
        $newSessionId = $request->session()->getId();

        $hadPreviousSession = false;

        // Update active_session_id with a database lock (same pattern as original controller)
        DB::transaction(function () use ($user, $newSessionId, &$hadPreviousSession) {
            $lockedUser = User::where('id', $user->id)->lockForUpdate()->first();
            if ($lockedUser) {
                if (! empty($lockedUser->active_session_id) && $lockedUser->active_session_id !== $newSessionId) {
                    $hadPreviousSession = true;
                }
                $lockedUser->setActiveSession($newSessionId);
            }
        });

        // Broadcast real-time SessionReplaced event (existing behavior preserved)
        if ($hadPreviousSession) {
            try {
                broadcast(new SessionReplaced($user->id))->toOthers();
            } catch (\Throwable $e) {
                logger()->warning('Failed to broadcast SessionReplaced after OTP: ' . $e->getMessage());
            }

            ActivityLog::create([
                'user_id'     => $user->id,
                'action'      => 'Session Replaced',
                'module'      => 'Authentication',
                'severity'    => ActivityLog::SEVERITY_WARNING,
                'result'      => ActivityLog::RESULT_SUCCESS,
                'description' => "Account {$user->email} completed OTP and replaced a previous active session.",
                'ip_address'  => $request->ip(),
                'logged_at'   => now(),
            ]);
        }

        // Audit: successful login (matching existing pattern exactly)
        ActivityLog::create([
            'user_id'     => $user->id,
            'action'      => 'Login',
            'module'      => 'Authentication',
            'severity'    => ActivityLog::SEVERITY_INFO,
            'result'      => ActivityLog::RESULT_SUCCESS,
            'description' => "User [{$user->email}] logged in successfully (OTP verified).",
            'ip_address'  => $request->ip(),
            'logged_at'   => now(),
        ]);

        // Generate encrypted login token (existing behavior preserved)
        $plainToken     = Str::random(64);
        $encryptedToken = encrypt($plainToken);
        $user->update(['login_token' => $encryptedToken]);

        // Reset any previous failed password attempts (existing behavior)
        $user->resetLoginAttempts();

        // Remember-email cookie handling was set at the password step — nothing to do here

        // Resolve role dashboard and redirect (same logic as original)
        $role           = $user->roles()->first();
        $dashboardRoute = $role?->dashboard_route;

        if ($dashboardRoute && Route::has($dashboardRoute)) {
            return redirect()->route($dashboardRoute);
        }

        return redirect()->route('dashboard');
    }

    // ─────────────────────────────────────────── Resend OTP ────────────────

    /**
     * Resend a new OTP to the user's email.
     *
     * Enforces 60-second cooldown and 5-sends-per-15-minute rate limit.
     * Generates a new OTP, invalidating the previous one.
     */
    public function resend(Request $request): RedirectResponse
    {
        $userId = $request->session()->get('otp_pending_user_id');

        if (! $userId) {
            return redirect()->route('login');
        }

        $user = User::find($userId);

        if (! $user || ! $user->is_active) {
            $request->session()->forget('otp_pending_user_id');
            return redirect()->route('login');
        }

        // ── Enforce cooldown ────
        if (! $this->otpService->canResend($user)) {
            $remaining = $this->otpService->resendCooldownRemaining($user);
            return redirect()->route('otp.verify')
                ->with('resend_error', "Please wait {$remaining} second(s) before requesting a new code.");
        }

        // ── Enforce rate limit (max 5 OTPs in 15 minutes) ────
        if ($this->otpService->isRateLimited($user)) {
            return redirect()->route('otp.verify')
                ->with('resend_error', 'You have requested too many verification codes. Please try again later.');
        }

        // Generate new OTP (invalidates the previous one)
        $plainOtp   = $this->otpService->generate($user);
        $expMinutes = config('otp.expires_minutes', 3);

        // Send via email
        try {
            Mail::to($user->email)->send(new OtpNotificationMail($plainOtp, $expMinutes));
        } catch (\Throwable $e) {
            logger()->error('OTP resend email failed: ' . $e->getMessage());
            return redirect()->route('otp.verify')
                ->with('resend_error', 'Failed to send verification code. Please try again.');
        }

        // Audit log for resend
        ActivityLog::create([
            'user_id'     => $user->id,
            'action'      => 'OTP Resent',
            'module'      => 'Authentication',
            'severity'    => ActivityLog::SEVERITY_INFO,
            'result'      => ActivityLog::RESULT_SUCCESS,
            'description' => "Verification code resent to account [{$user->email}].",
            'ip_address'  => $request->ip(),
            'logged_at'   => now(),
        ]);

        return redirect()->route('otp.verify')
            ->with('resend_success', 'A new verification code has been sent to your email.');
    }
}
