@extends('layouts.print')

@section('title', 'System User Governance Report')
@section('department', 'Office of System Administration & Security Governance')
@section('document-title', 'USER DIRECTORY REPORT')
@section('document-no', 'ADM-USR-' . date('Ymd'))

@section('page-orientation', 'landscape')

@section('content')
<!-- Administrative Header Summary -->
<div class="patient-info-box">
    <div class="row g-2">
        <div class="col-3">
            <div class="info-label">Report Category</div>
            <div class="info-value">User Accounts Audit</div>
        </div>
        <div class="col-3">
            <div class="info-label">Total Users</div>
            <div class="info-value fw-bold text-primary">{{ $users->count() }}</div>
        </div>
        <div class="col-3">
            <div class="info-label">Generated By</div>
            <div class="info-value">{{ auth()->user()->name }} (Admin)</div>
        </div>
        <div class="col-3">
            <div class="info-label">Date Generated</div>
            <div class="info-value">{{ now()->format('M d, Y h:i A') }}</div>
        </div>
    </div>
</div>

<!-- Users Table -->
<h6 class="fw-bold mb-2 text-uppercase text-secondary" style="font-size: 11px; letter-spacing: 0.04em;">Authorized HIMS System Users</h6>
<table class="table-clinical">
    <thead>
        <tr>
            <th style="width: 5%;">#</th>
            <th style="width: 25%;">User Name</th>
            <th style="width: 25%;">Email Address</th>
            <th style="width: 20%;">Assigned Clinical Role</th>
            <th style="width: 15%;">Account Status</th>
            <th style="width: 10%;">Created Date</th>
        </tr>
    </thead>
    <tbody>
        @forelse($users as $index => $user)
        <tr>
            <td>{{ $index + 1 }}</td>
            <td class="fw-bold">{{ $user->name }}</td>
            <td>{{ $user->email }}</td>
            <td>
                @foreach($user->roles as $role)
                <span class="badge bg-primary bg-opacity-10 text-primary border me-1">{{ $role->name }}</span>
                @endforeach
            </td>
            <td>
                @if($user->trashed())
                <span class="badge bg-danger bg-opacity-10 text-danger border">Disabled</span>
                @else
                <span class="badge bg-success bg-opacity-10 text-success border">Active</span>
                @endif
            </td>
            <td>{{ $user->created_at->format('M d, Y') }}</td>
        </tr>
        @empty
        <tr>
            <td colspan="6" class="text-center text-muted">No users found.</td>
        </tr>
        @endforelse
    </tbody>
</table>

<!-- Signatures -->
<div class="row pt-5 text-center">
    <div class="col-6">
        <div class="signature-line">
            {{ auth()->user()->name }}
        </div>
        <div class="text-muted small" style="font-size: 10px;">System Administrator</div>
    </div>
    <div class="col-6">
        <div class="signature-line">
            Chief Information Officer / Director
        </div>
        <div class="text-muted small" style="font-size: 10px;">IT & Hospital Security Governance</div>
    </div>
</div>
@endsection
