<?php

namespace App\AI;

use App\Contracts\AIProviderInterface;

/**
 * MockAIProvider — Stage 1 Development & Testing Provider for Virtual MediSense AI.
 *
 * PURPOSE:
 * This class exists solely to verify that the MediSense architecture correctly
 * receives patient-specific clinical context from ClinicalContextBuilder and
 * passes it through the AIProviderInterface pipeline.
 *
 * THIS IS NOT A CLINICAL AI PROVIDER.
 * - No external AI service is called.
 * - No medical reasoning is performed.
 * - No diagnoses, treatments, or clinical orders are generated.
 * - No hard-coded symptom → diagnosis rules exist.
 * - All output is clearly labeled Stage 1 Development/Test.
 *
 * When a real provider (e.g. EvidenceMD) is configured, this class is replaced
 * without modifying any controller, service, or view.
 */
class MockAIProvider implements AIProviderInterface
{
    public const PROVIDER_NAME = 'Mock AI Provider';
    public const STATUS_DEV    = 'Stage 1 — Development/Test Mode';

    public function analyzeClinicalContext(string $task, array $context): array
    {
        $patient  = $context['patient'] ?? [];
        $name     = $patient['full_name']   ?? 'Selected Patient';
        $no       = $patient['patient_no']  ?? 'N/A';
        $age      = $patient['age']         ?? 'N/A';
        $gender   = $patient['gender']      ?? 'N/A';
        $type     = $patient['patient_type'] ?? 'N/A';
        $findings = $context['symptoms_and_findings'] ?? 'No clinical findings recorded.';

        $labCount  = count($context['recent_lab_results']       ?? []);
        $radCount  = count($context['recent_radiology_reports'] ?? []);
        $rxCount   = count($context['active_prescriptions']     ?? []);
        $surgCount = count($context['surgery_requests']         ?? []);
        $dietCount = count($context['diet_requests']            ?? []);

        $taskLabels = [
            'SYMPTOM_ASSESSMENT'          => 'Symptom Assessment',
            'DIAGNOSTIC_ASSISTANCE'       => 'Diagnostic Assistance',
            'TREATMENT_RECOMMENDATION'    => 'Treatment Recommendation',
            'CLINICAL_SERVICE_ASSISTANCE' => 'Clinical Service Assistance',
        ];
        $taskLabel = $taskLabels[$task] ?? $task;

        $disclaimer = 'MediSense is a clinical decision-support component. '
            . 'Information generated by an AI provider is intended to assist '
            . 'the attending Doctor and does not replace professional clinical judgment. '
            . 'The attending Doctor remains responsible for all final clinical decisions, '
            . 'diagnoses, treatments, and orders.';

        return [
            'task'     => $task,
            'provider' => self::PROVIDER_NAME,
            'status'   => self::STATUS_DEV,

            // Summary shown at the top of the result card
            'summary' => "Stage 1 verification: {$taskLabel} request received for {$name} ({$no}). "
                . 'The MediSense pipeline executed successfully. No AI clinical reasoning was performed.',

            // What the context pipeline received
            'context_received' => [
                'patient_name'  => $name,
                'patient_no'    => $no,
                'age'           => $age,
                'gender'        => $gender,
                'patient_type'  => $type,
                'ward'          => ($patient['ward'] ?? null) ? "{$patient['ward']}" . ($patient['bed_number'] ? " / Bed {$patient['bed_number']}" : '') : null,
            ],

            // Clinical findings received as-is (not interpreted)
            'findings_received' => $findings,

            // Raw context counts — only what ClinicalContextBuilder actually queried
            'hims_context' => [
                'laboratory_results'  => $labCount,
                'radiology_reports'   => $radCount,
                'active_prescriptions' => $rxCount,
                'surgery_requests'    => $surgCount,
                'diet_requests'       => $dietCount,
            ],

            // Data provenance — only list modules actually queried
            'evidence' => [
                'Clinical Context Builder v1 — HIMS data aggregation',
                'LIS — Laboratory results queried',
                'RIS — Radiology reports queried',
                'PMS — Prescription records queried',
                'SORS — Surgery records queried',
                'DNMS — Diet/nutrition records queried',
                'Stage 1 Mock Provider — Pipeline verification only',
            ],

            'disclaimer' => $disclaimer,

            // Legacy keys kept empty so the JS renderer produces no clinical sections
            'clinical_considerations'         => [],
            'diagnostic_considerations'       => [],
            'treatment_considerations'        => [],
            'clinical_service_considerations' => [],
        ];
    }
}
